#define F_PINMODE                   1
#define F_DIGITALWRITE              2
#define F_DIGITALREAD               3
#define F_ANALOGWRITE               4
#define F_ANALOGREAD                5
#define F_ANALOGREFERENCE           6
#define F_TONE_int_int              7
#define F_TONE_int_int_long         8
#define F_NOTONE                    9
#define F_SHIFTOUT                 10
#define F_SHIFTIN                  11
#define F_PULSEIN_int_int          12
#define F_PULSEIN_int_int_long     13
#define F_DELAY                    14
#define F_DELAYMICROSECONDS        15
#define F_ATTACHINTERRUPT          16
#define F_DETACHINTERRUPT          17
#define F_INTERRUPTS               18
#define F_NOINTERRUPTS             19
#define F_SERIAL_BEGIN             20
#define F_SERIAL_END               22
#define F_SERIAL_AVAILABLE         23
#define F_SERIAL_READ              24
#define F_SERIAL_PEEK              25
#define F_SERIAL_FLUSH             26
#define F_SERIAL_PRINT_int         27
#define F_SERIAL_PRINT_int_int     28
#define F_SERIAL_PRINT_char        29
#define F_SERIAL_PRINTLN_int       30
#define F_SERIAL_PRINTLN_char      31
#define F_SERIAL_PRINTLN_String    32
#define F_SERIAL_WRITE             33
#define F_LOOP                     99 

